################################################
# EBSI BESU REGULAR NODE
################################################

FROM hyperledger/besu:develop

# Start Pantheon with the config file
CMD ["--config-file=/root/besu/config/config.toml"]
