################################################
# PANTHEON ALASTRIA REGULAR NODE
################################################

FROM hyperledger/besu:develop

# Start Pantheon with the config file
ENTRYPOINT ["/opt/pantheon/bin/pantheon"]
CMD ["--config-file=/root/besu/config/config.toml"]
